version: '3.5'

volumes:
  bundle: {}
  pgdata: {}

services:
  app:
    image: ruby:2.2.4
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    working_dir: /app
    depends_on:
      - database

  database:
    image: postgres:9.5
    networks:
      default: {}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
